<?php
/**
 * Created by PhpStorm.
 * User: Daniel
 * Date: 26/09/2018
 * Time: 12:06
 */


class App extends MY_Controller {

    protected function middleware()
    {
        return array('system_auth|except:login'); // TODO: Change the autogenerated stub
    }

    public function index(){
       if ($this->session->userdata('staff_id')){
           $data = array(
               'first_name'=> $this->session->userdata('first_name')
           );
           $this->load->view('workspace',$data);
       }else{
           redirect(base_url('app/login'));
       }
   }

   public function login(){

         $url = $this->input->post('url');
         $data = array('url'=>$url);

         $username = $this->input->post('username');
         $password = $this->input->post('password');

       if ($username && $password){
           $this->load->model('user');
           $users = new User();
           $users = $this->user->get(1,0,array(
               'username'=> $username,
               'password'=>$password
           ));
           if(!empty($users)){
               $found_user = array_shift($users);

               $this->load->model('staff');
               $staff = new Staff();
               $staff = $this->staff->get(1,0,array('id'=>$found_user->staff_id));
               $found_staff = array_shift($staff);

               $userdata = array(
                   'full_name'=>$found_staff->full_name(),
                   'first_name'=>ucfirst($found_staff->first_name),
                   'middle_name'=>ucfirst(substr($found_staff->middle_name,0,1)),
                   'last_name'=>ucfirst($found_staff->last_name),
                   'staff_id'=>$found_staff->{$found_staff::DB_TABLE_PK},
                   'avatar_path'=>$found_staff->avatar_path()
               );
               $this->session->set_userdata($userdata);
              redirect(base_url($url));

           }else {
               $this->load->view('login',$data);
           }
         }else{
           $this->load->view('login',$data);
       }

   }

   public function logout(){
       $this->session->sess_destroy();
       redirect(base_url());
   }

}