<?php
/**
 * Created by PhpStorm.
 * User: alfred soso
 * Date: 3/14/2019
 * Time: 3:14 PM
 */
class Finances extends MY_Controller{

	protected function middleware()
	{
		return array('system_auth'); // TODO: Change the autogenerated stub
	}

	public function account_receivable(){
		$this->load->model('account_group');
		$this->load->model('account');

		$group = new Account_group();
		$group = $this->account_group->get(0,0,array('group_nature_id'=>2));

		$account = new Account();
		$account = $this->account->get();

		inspect_object(array_shift($group));exit();

		if(array_shift($account)->account_group_id == array_shift($group)){
			//$this->load->view('finances/account_receivable/account_receivable_list');
			echo 'yeahhh';
		}else{
			redirect(base_url());
		}
	}


}
